# Generated by Django 5.2 on 2025-05-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NCModel', models.ImageField(upload_to='nc_img/')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='content_img',
            field=models.ImageField(upload_to='content_img/'),
        ),
    ]
