# Generated by Django 5.2 on 2025-05-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_ncmodel_alter_content_content_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt_img', models.ImageField(upload_to='self_img/')),
            ],
        ),
    ]
