# Generated by Django 5.2 on 2025-05-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_geric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ncmodel',
            old_name='NCModel',
            new_name='nc_img',
        ),
    ]
