# Generated by Django 5.2 on 2025-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_landscapeprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscapeprojects',
            name='landscape_project_img',
            field=models.ImageField(upload_to='landscape_projects_img/'),
        ),
    ]
